name: CI/CD CRF containers & models

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# env:
#   PROJECT_ID: ${{ secrets.GCE_PROJECT }}
#   GCS_SERVICE_ACCOUNT: ${{ secrets.GCE_SA_KEY }}

jobs:
  ci:
    name: Java CI 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify --file code/java/crf-utility/pom.xml

  check-ncbi-disease:
    runs-on: ubuntu-latest
    needs: ci
    outputs:
      status: ${{ steps.early.conclusion }}
    steps:
      - id: ncbi-disease_file_changes
        uses: trilom/file-changes-action@v1.2.4
        with: 
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: skip-ncbi-disease
        run: ls -la

  model-publish-crf-ncbi-disease:
    runs-on: ubuntu-latest
    needs: check-ncbi-disease
    if: needs.check-ncbi-disease.status == 'success'
    name: Publish Disease CRF model
    steps:
      - id: echo
        name: echo check
        run: echo "Running model publish!"
        


  #   runs-on: ubuntu-latest
  #   env:
  #     DOCKERFILE: ncbi-disease.crf.Dockerfile
  #     GCE_MACHINE_TYPE: n1-highmem-16
  #     GCE_REGION: us-central1
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         ref: master